"""
Enumerations for data contracts.
"""

from enum import StrEnum


class ConfidenceLevel(StrEnum):
    """Levels of derived confidence."""

    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class SeverityLevel(StrEnum):
    """Severity levels for anomalies."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SignalCategory(StrEnum):
    """Category of candidate signal."""

    STRENGTH = "STRENGTH"
    RISK = "RISK"


class CandidateSignalType(StrEnum):
    """Types of candidate intelligence signals."""

    HIGH_SKILL_DENSITY = "HIGH_SKILL_DENSITY"
    STRONG_TECHNICAL_DEPTH = "STRONG_TECHNICAL_DEPTH"
    MULTI_DOMAIN_EXPERTISE = "MULTI_DOMAIN_EXPERTISE"
    LEADERSHIP_BACKGROUND = "LEADERSHIP_BACKGROUND"
    CONSISTENT_CAREER_GROWTH = "CONSISTENT_CAREER_GROWTH"
    INCOMPLETE_PROFILE = "INCOMPLETE_PROFILE"
    LIMITED_EXPERIENCE = "LIMITED_EXPERIENCE"
    SKILL_FRAGMENTATION = "SKILL_FRAGMENTATION"
    MISSING_CERTIFICATIONS = "MISSING_CERTIFICATIONS"


class EntityType(StrEnum):
    """Types of extracted entities."""

    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    LOCATION = "LOCATION"
    TECHNOLOGY = "TECHNOLOGY"
    SKILL = "SKILL"
    CERTIFICATION = "CERTIFICATION"
    PROJECT = "PROJECT"
    PRODUCT = "PRODUCT"
    IDENTIFIER = "IDENTIFIER"
    UNKNOWN = "UNKNOWN"


class PatternType(StrEnum):
    """Types of discovered patterns."""

    CO_OCCURRENCE = "CO_OCCURRENCE"
    SEQUENCE = "SEQUENCE"
    TRANSITION = "TRANSITION"
    HIERARCHY = "HIERARCHY"
    REPEATED_STRUCTURE = "REPEATED_STRUCTURE"


class AnomalyType(StrEnum):
    """Types of discovered anomalies."""

    STRUCTURAL = "STRUCTURAL"
    STATISTICAL = "STATISTICAL"
    TEMPORAL = "TEMPORAL"
    SEMANTIC = "SEMANTIC"
    RELATIONSHIP = "RELATIONSHIP"
    QUALITY = "QUALITY"


class RelationshipType(StrEnum):
    """Types of inferred relationships."""

    WORKED_AT = "WORKED_AT"
    HAS_SKILL = "HAS_SKILL"
    LOCATED_IN = "LOCATED_IN"
    OWNS = "OWNS"
    CREATED = "CREATED"
    EARNED = "EARNED"
    USES = "USES"


class DirectionType(StrEnum):
    """Directionality of relationships."""

    DIRECTED = "DIRECTED"
    BIDIRECTIONAL = "BIDIRECTIONAL"


class ArtifactType(StrEnum):
    """All generated artifact types."""

    DATASET_RECORD = "DATASET_RECORD"
    SCHEMA_GRAPH = "SCHEMA_GRAPH"
    PROFILE_REPORT = "PROFILE_REPORT"
    SEMANTIC_CATALOG = "SEMANTIC_CATALOG"
    ENTITY_CATALOG = "ENTITY_CATALOG"
    RELATIONSHIP_CATALOG = "RELATIONSHIP_CATALOG"
    PATTERN_CATALOG = "PATTERN_CATALOG"
    CLUSTER_CATALOG = "CLUSTER_CATALOG"
    ANOMALY_CATALOG = "ANOMALY_CATALOG"
    INTELLIGENCE_REPORT = "INTELLIGENCE_REPORT"
    INTELLIGENCE_SUMMARY = "INTELLIGENCE_SUMMARY"
    SCHEMA_FIELD = "SCHEMA_FIELD"
    PROFILE_METRIC = "PROFILE_METRIC"
    SEMANTIC_CONCEPT = "SEMANTIC_CONCEPT"
    ENTITY = "ENTITY"
    RELATIONSHIP = "RELATIONSHIP"
    PATTERN = "PATTERN"
    CLUSTER = "CLUSTER"
    ANOMALY = "ANOMALY"
    RECOMMENDATION = "RECOMMENDATION"
    ARTIFACT_REGISTRY = "ARTIFACT_REGISTRY"
    CANDIDATE_PROFILE = "CANDIDATE_PROFILE"
    CANDIDATE_SIGNAL = "CANDIDATE_SIGNAL"
    CANDIDATE_CATALOG = "CANDIDATE_CATALOG"
    CANDIDATE_INTELLIGENCE_CATALOG = "CANDIDATE_INTELLIGENCE_CATALOG"
    KNOWLEDGE_GRAPH = "KNOWLEDGE_GRAPH"
    ENTITY_CENTRALITY_CATALOG = "ENTITY_CENTRALITY_CATALOG"
    JOB_INTELLIGENCE_CATALOG = "JOB_INTELLIGENCE_CATALOG"
    ALIGNMENT_CATALOG = "ALIGNMENT_CATALOG"
    SCORING_CATALOG = "SCORING_CATALOG"
    CANDIDATE_JOB_SCORE = "CANDIDATE_JOB_SCORE"
    RANKED_CANDIDATE_CATALOG = "RANKED_CANDIDATE_CATALOG"


class NodeType(StrEnum):
    """Types of nodes in the Knowledge Graph."""

    CANDIDATE = "CANDIDATE"
    SKILL = "SKILL"
    COMPANY = "COMPANY"
    ROLE = "ROLE"
    EDUCATION = "EDUCATION"
    CERTIFICATION = "CERTIFICATION"
    LANGUAGE = "LANGUAGE"
    PATTERN = "PATTERN"
    CLUSTER = "CLUSTER"
    ANOMALY = "ANOMALY"


class EdgeType(StrEnum):
    """Types of edges in the Knowledge Graph."""

    POSSESSES_ENTITY = "POSSESSES_ENTITY"
    EXHIBITS_PATTERN = "EXHIBITS_PATTERN"
    BELONGS_TO_CLUSTER = "BELONGS_TO_CLUSTER"
    HAS_ANOMALY = "HAS_ANOMALY"
    RELATED_TO = "RELATED_TO"
    ROLE_REQUIRES_SKILL = "ROLE_REQUIRES_SKILL"
    LANGUAGE_HAS_PROFICIENCY = "LANGUAGE_HAS_PROFICIENCY"
    COMPANY_SIZE_OF_EMPLOYER = "COMPANY_SIZE_OF_EMPLOYER"
    DEGREE_RELATES_TO_SKILL = "DEGREE_RELATES_TO_SKILL"
    SKILL_CO_OCCURS_WITH_SKILL = "SKILL_CO_OCCURS_WITH_SKILL"


class SourceType(StrEnum):
    """Source origin of a dataset record."""

    CSV = "CSV"
    JSON = "JSON"
    JSONL = "JSONL"
    PARQUET = "PARQUET"
    DATABASE = "DATABASE"
    API = "API"
    STREAM = "STREAM"
    UNKNOWN = "UNKNOWN"


class FieldType(StrEnum):
    """Discovered data type of a schema field."""

    STRING = "STRING"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    TIMESTAMP = "TIMESTAMP"
    ARRAY = "ARRAY"
    OBJECT = "OBJECT"
    UNKNOWN = "UNKNOWN"


class MetricType(StrEnum):
    """Statistical metric types."""

    NULLABILITY = "NULLABILITY"
    CARDINALITY = "CARDINALITY"
    DISTRIBUTION = "DISTRIBUTION"
    UNIQUENESS = "UNIQUENESS"
    ENTROPY = "ENTROPY"
    FREQUENCY = "FREQUENCY"
    MIN = "MIN"
    MAX = "MAX"
    MEAN = "MEAN"
    MEDIAN = "MEDIAN"
    STDDEV = "STDDEV"
    MODE = "MODE"
    UNKNOWN = "UNKNOWN"
